// ZRM (Zespoły Ratownictwa Medycznego) — official substance list
export const ZRM_SUBSTANCES = [
  "Adenozyna",
  "Adrenalina",
  "Amiodaron",
  "Atropina siarczanowa",
  "Budesonid",
  "Deksmethason",
  "Diazepam",
  "Drotaweryna chlorowodorek",
  "Fentanyl",
  "Flumazenil",
  "Furosemidum",
  "Glukagon",
  "Glukoza 20%",
  "Glukoza 5%",
  "Heparyna",
  "Hydrokortyzon",
  "Hydroksyetyloskrobia",
  "Hydroksyzyny chlorowodorek",
  "Ibuprofenum",
  "Izosorbidu mononitras",
  "Kaptoprylum",
  "Ketoprofenum",
  "Klemastini fumaras",
  "Klonazepamum",
  "Klopidogrel",
  "Kwas acetylosalicylowy",
  "Kwas traneksamowy",
  "Lidokainy chlorowodorek",
  "Siarczan magnezu",
  "Mannitolum 15%",
  "Metamizolum",
  "Metoklopramididum",
  "Metoprololu tartras",
  "Midazolamum",
  "Morfina chlorowodorek",
  "Nalokson",
  "Nitrogliceryna",
  "Noradrenaliny kwas winian",
  "Papaweryni chlorowodorek",
  "Paracetamolum",
  "Płyn fizjologiczny wieloelektrolitowy izotoniczny",
  "Prasugrel",
  "Roztwór Ringera",
  "Salbutamolum",
  "Natrii chloridum 0,9%",
  "Tiethylperazini chlorowodorek",
  "Tikagrelor",
  "Tlen medyczny",
  "Urapidilum",
  "Natrii wodorowęglanian 8,4%",
  "Żelatyna modyfikowana"
];

// Common forms used in EMS
export const DRUG_FORMS = [
  "roztwór do wstrzykiwań",
  "roztwór do infuzji",
  "tabletki",
  "tabletki do żucia",
  "tabletki powlekane",
  "kapsułki",
  "ampułki",
  "ampułko-strzykawki",
  "aerozol do inhalacji",
  "zawiesina do nebulizacji",
  "aerozol podjęzykowy",
  "żel doodbytniczy",
  "roztwór doustny",
  "wlewka doodbytnicza",
  "gaz medyczny",
  "roztwór do infuzji dożylnej",
  "proszek do sporządzania roztworu",
  "inne"
];

// Common units for quantity tracking
export const DRUG_UNITS = [
  "amp.",
  "tabl.",
  "kaps.",
  "fiol.",
  "but.",
  "szt.",
  "ml",
  "l",
  "worki",
  "neb.",
  "dawki",
  "inne"
];
